version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "LambdaBase"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-vudbwwiekb0u"
s3_prefix = "LambdaBase"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ApplicationName=\"lambda-base\" ApiStageName=\"dev\""
