AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-base

  Example SAM Template for lambda-base
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: nodejs12.x
    CodeUri: dist/
    Timeout: 3
  
Parameters:
  ApplicationName:
    Type: String
    Default: lambda-base
  ApiStageName:
    Type: String
    Default: dev

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Sub ${ApplicationName}-HelloWorldFunction
      Handler: lambda.handle
      # Environment:
      #   Variables:
      # Policies:
      # Events:

Outputs:
  HelloWorldFunctionARN:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
